Prototype
stratis-storage/stratisd pull request #2136
Opened 2020-07-20 20:57 UTC by jbaublitz

Prototype for #2134

2020-07-21 14:53 UTC, jbaublitz commented
@mulkieran I've rebased and resolved conflicts to take advantage of the `extras` feature and new Makefile target. Let me know if we need to split it out into two different features when I request review. Doing a last little bit of review first.

2020-07-21 14:53 UTC, jbaublitz commented
Rebased again.

2020-07-22 15:11 UTC, jbaublitz commented
Rebased.

2020-07-31 14:26 UTC, jbaublitz commented
Rebased and merge conflicts resolved.

2020-08-11 15:41 UTC, jbaublitz commented
Blocked by #2163

2020-08-12 13:08 UTC, mulkieran commented
@jbaublitz Please rebase when convenient.

2020-08-12 21:02 UTC, mulkieran commented
I'll review this more thoroughly once #2163 clears.

2020-09-22 13:35 UTC, mulkieran requested changes
Two minor requests...

2020-09-22 13:35 UTC, mulkieran commented on src/bin/stratis-min/key.rs
> +pub fn key_set(key_desc: &str, keyfile_path: Option<&str>, no_tty: bool) -> StratisResult<()> {
Please add some docs for this method.

2020-09-22 14:46 UTC, jbaublitz commented
@mulkieran I've addressed the two concerns you had.

2020-09-22 16:26 UTC, mulkieran requested changes
Looks good! Please close this and open a final PR.

2020-09-22 17:12 UTC, closed without merging