Prototype of potential workaround for D-Bus connection hang up
stratis-storage/stratisd pull request #2286
Opened 2020-10-30 19:22 UTC by jbaublitz

Related to stratis-storage/project#237

2020-11-03 12:21 UTC, jbaublitz commented
@mulkieran I've switched to a non-blocking way of checking if there are more bytes available after `STRATIS_MAX_PASS_SIZE` is reached. The previous way in the PR would have had the same hanging problem if the user provided _exactly_ `STRATIS_MAX_PASS_SIZE` bytes in a terminal as it would read exactly that many bytes, trigger the if statement, and then if the file descriptor were blocking, the `.next()` call on the byte iterator would block as there would be no more data left to read. This change will ensure that we get the appropriate information without ever blocking.

2020-11-03 14:45 UTC, mulkieran commented
> @mulkieran I've switched to a non-blocking way of checking if there are more bytes available after `STRATIS_MAX_PASS_SIZE` is reached. The previous way in the PR would have had the same hanging problem if the user provided _exactly_ `STRATIS_MAX_PASS_SIZE` bytes in a terminal as it would read exactly that many bytes, trigger the if statement, and then if the file descriptor were blocking, the `.next()` call on the byte iterator would block as there would be no more data left to read. This change will ensure that we get the appropriate information without ever blocking.

Great! Thanks for catching that. AFAICT, nothing that a caller can do could now cause this chunk of code to hang.

2020-11-03 17:43 UTC, mulkieran reviewed
Looks good.

2020-11-05 12:38 UTC, mvollmer approved these changes
This works fine for the Cockpit Stratis PoC. I have tested it together with https://github.com/stratis-storage/stratis-cli/pull/670.

2020-11-05 16:12 UTC, mulkieran requested changes
jbaublitz: Please close this and prepare a final PR.

2020-11-05 16:43 UTC, closed without merging