Issue project 192
stratis-storage/stratisd pull request #2306
Opened 2020-11-13 16:31 UTC by jbaublitz

Supersedes #2253

2020-11-13 17:26 UTC, mulkieran requested changes
typo...

2020-11-13 17:26 UTC, mulkieran commented on src/engine/strat_engine/backstore/blockdevmgr.rs
> +        // Liminal device code will note set up a pool with multiple key description
^note^not

2020-11-16 18:27 UTC, jbaublitz commented on src/engine/strat_engine/backstore/blockdevmgr.rs
> +        // Liminal device code will note set up a pool with multiple key description
Resolved.

2020-11-16 18:32 UTC, jbaublitz commented
- [ ] Take key_desc out of BlockDevMgr struct
- [ ] Stow Clevis config information in every StratBlockDev
- [ ] Handle setting of the Clevis config information in the StratBlockDev after a bind operation
- [ ] Export the Clevis config for a pool via the FetchProperties interface over the D-Bus
- [ ] Handle getting the Clevis config during an add operation

2020-11-16 18:42 UTC, jbaublitz commented
@mulkieran I'm leaving the method `CryptHandle::clevis_info()` and allowing the dead code as you will need that for your work in the liminal devices code.

2020-11-16 22:17 UTC, jbaublitz commented
I'm going to do one more pass but I've tested the bind command, the report generated for both the sim and strat engine, and everything seems to be working (including unlock; @drckeefe, I was unable to reproduce your issue with real devices, but please let me know if you have a way to).

@mulkieran If you want to work on the part of this, please go ahead and I'll put mine in review once it's ready.

2020-11-19 16:12 UTC, closed without merging