Rework Table for use with multiple types
stratis-storage/stratisd pull request #2340
Opened 2020-12-05 12:36 UTC by jbaublitz

Supersedes #2321

2021-01-28 02:05 UTC, mulkieran commented
@jbaublitz Could you rebase and resolve the minor conflicts? We will aim to get this in in the next release, if at all possible.

2021-01-28 16:15 UTC, jbaublitz commented
Rebased!

2021-01-29 03:01 UTC, mulkieran requested changes
It looks good to me so far. But looking back I remember it was all in aid of making this work: https://github.com/stratis-storage/stratisd/pull/2288/files. Right here: https://github.com/stratis-storage/stratisd/pull/2288/files was where we realized that we wanted ```PoolUuid``` to be its own type, not just a type alias, so that we could do similar but different impls of ```Display``` for ```CreateAction<FilesystemUuid>``` and ```CreateAction<DevUuid>``` for example. And the problem was that if we did that, we'ld have to implement some methods on each of these types, like ```to_simple_ref()``` etc.

I'm afraid you'll have to remind me of what the plan was to solve that problem.

2021-01-29 15:43 UTC, jbaublitz commented on src/engine/strat_engine/cleanup.rs
> +// This Source Code Form is subject to the terms of the Mozilla Public
Whoops! I'll remove this.

2021-01-29 15:45 UTC, jbaublitz commented
I think the plan to solve this was to implement `AsUuid` for all of the UUID wrapped types and simply call `.as_uuid()` on those structs and use the existing methods. Is that still what you want to do?

2021-01-29 17:06 UTC, mulkieran commented
> I think the plan to solve this was to implement `AsUuid` for all of the UUID wrapped types and simply call `.as_uuid()` on those structs and use the existing methods. Is that still what you want to do?

That would be fine w/ me. The other way is to use default methods in the AsUuid trait for the few methods that we actually use, which might be less intrusive. So, something like:

```
trait AsUuid {
  fn as_uuid(&self) -> &Uuid;

  fn to_simple_ref(&self) -> SimpleRef {
    self.as_uuid().to_simple_ref()
  }

  // any other funcs, hopefully few
}

#[derive(...)]
struct PoolUuid(Uuid);

impl AsUuid for PoolUuid {
  fn as_uuid(&self) -> &Uuud {
    &self.0
 }
}
```

2021-01-30 01:06 UTC, mulkieran commented
We also might use Deref, or possibly a trait bounded by Deref.

2021-02-01 16:49 UTC, jbaublitz commented on src/engine/strat_engine/cleanup.rs
> +// This Source Code Form is subject to the terms of the Mozilla Public
Resolved!

2021-02-01 21:43 UTC, jbaublitz commented
@mulkieran I found the bug. It boils down to the XFS CLI expecting dashes in the UUID while our output on disk is without dashes. This raises an interesting question about the `Display` trait for our wrapper types. Should those display the output with dashes and we can continue calling `.to_simple_ref()` if we need it without dashes? That seems consistent with what we previously did and maybe it's best to leave it that way.

2021-02-01 23:16 UTC, mulkieran commented
> @mulkieran I found the bug. It boils down to the XFS CLI expecting dashes in the UUID while our output on disk is without dashes. This raises an interesting question about the `Display` trait for our wrapper types. Should those display the output with dashes and we can continue calling `.to_simple_ref()` if we need it without dashes? That seems consistent with what we previously did and maybe it's best to leave it that way.

I think that's the correct decision.

2021-02-02 14:07 UTC, jbaublitz commented
Okay, then I think this is ready for review. Moving.

2021-02-02 17:03 UTC, mulkieran requested changes
Looks great! Just two requests...

Do you want to merge this PR as soon as it's ready, or do you want to add the macro work on to this PR as a separate commit?

2021-02-02 17:07 UTC, jbaublitz commented
> Looks great! Just two requests...
> 
> Do you want to merge this PR as soon as it's ready, or do you want to add the macro work on to this PR as a separate commit?

I think the macro work as a separate commit might be for the best just in case I need to change anything.

2021-02-02 17:11 UTC, mulkieran commented
> > Looks great! Just two requests...
> > Do you want to merge this PR as soon as it's ready, or do you want to add the macro work on to this PR as a separate commit?
> 
> I think the macro work as a separate commit might be for the best just in case I need to change anything.

Sounds good.

2021-02-02 17:35 UTC, jbaublitz commented on src/dbus_api/pool/pool_2_0/methods.rs
> +                op.get_data().as_ref().and_then(|d| match d.uuid {
Resolved.

2021-02-02 17:35 UTC, jbaublitz commented on src/dbus_api/api/manager_2_0/methods.rs
> +        Some(StratisUuid::Pool(uuid)) => *uuid,
Resolved.

2021-02-02 17:42 UTC, mulkieran commented
@jbaublitz Looks good! Please carry on with macro work.

2021-02-03 14:56 UTC, jbaublitz commented
@mulkieran The prototype is done. I have some suggestions for how we can add additional logging information based on what I saw of the return types contained inside the data structures like `CreateAction` for some methods. You can already see an example of what I'm suggesting in the `impl` for `impl Display for DeleteAction<Key>` vs. `impl Display for DeleteAction<Clevis>`.

@drckeefe Take a look at the logs and see what you think.

2021-02-03 22:18 UTC, mulkieran commented
We're still not getting the output we wanted...that must be because the env variable isn't being properly observed. I'm going to try to come up with a fix for that in stratis-cli.

2021-02-04 01:45 UTC, mulkieran commented
> We're still not getting the output we wanted...that must be because the env variable isn't being properly observed. I'm going to try to come up with a fix for that in stratis-cli.

cli-with-stratisd test is all ready now. @drckeefe @bgurney-rh please take a look.

2021-02-08 16:26 UTC, bgurney-rh approved these changes

2021-02-08 16:41 UTC, mulkieran requested changes
Noticed one thing...design looks great to me.

2021-02-08 16:41 UTC, mulkieran commented on src/engine/engine.rs
> +    ) -> StratisResult<MappingCreateAction<Key>>;
Need to fix up header docs to match.

2021-02-08 20:37 UTC, jbaublitz commented on src/engine/engine.rs
> +    ) -> StratisResult<MappingCreateAction<Key>>;
Resolved.

2021-02-09 18:19 UTC, drckeefe approved these changes

2021-02-10 19:50 UTC, mulkieran commented
Ok! In standup we decided that we will format UUIDs in log messages and in the result of the engine state report with hyphens. So the changes currently in this PR will remain and some to_simple_ref() calls will have to be removed in various places.

2021-02-10 21:30 UTC, jbaublitz commented
@mulkieran Okay I think this is all set.

2021-02-11 00:55 UTC, mulkieran requested changes
There's one thing I forgot...can you remove ```name``` and ```uuid``` from ```TestThing``` definition. I think they exist because they were a mandatory part of the value object in the original Table struct. But since they aren't anymore, and aren't used to test for anything anywhere, they should be removed.

2021-02-11 19:49 UTC, jbaublitz commented
@mulkieran Okay this should be ready.

2021-02-11 19:57 UTC, mulkieran requested changes
Looks good. Please close this and open a new PR for final review.

2021-02-11 20:55 UTC, closed without merging