Prototype of Mutex-protected crypt module
stratis-storage/stratisd pull request #2388
Opened 2021-01-25 13:49 UTC by jbaublitz

Related to #2277 
Related to #2382 
Related to #2355

2021-01-25 14:50 UTC, jbaublitz commented
CI passed! Putting up for review.

2021-01-27 01:56 UTC, mulkieran requested changes
This looks correct to me, and I believe the mutex approach will be less restrictive than the assertion approach but just as correct. There is one unnecessary formatting change, I think.

2021-01-27 01:56 UTC, mulkieran commented on src/engine/strat_engine/backstore/crypt.rs
> +                        in the current environment. This may be due to an expired \
Wierd looking extra spaces.

2021-01-27 13:52 UTC, jbaublitz commented on src/engine/strat_engine/backstore/crypt.rs
> +                        in the current environment. This may be due to an expired \
Resolved.

2021-01-27 15:30 UTC, mulkieran requested changes
Looks ready then. Please close this PR and open a new one for final review.

2021-01-28 18:26 UTC, jbaublitz commented
I need to make one last change to this. I'll explain in stand up.

2021-02-02 17:32 UTC, closed without merging

2021-02-02 17:34 UTC, jbaublitz commented
Obsoleted by stratis-storage/libcryptsetup-rs#121