Fix EBUSY errors in loopback device test cleanup
stratis-storage/stratisd pull request #2432
Opened 2021-03-08 16:55 UTC by jbaublitz

Related to #2427

2021-03-08 17:35 UTC, jbaublitz commented
@mulkieran Okay excellent! This is ready for review. Proof that the retries are working is [here](https://github.com/stratis-storage/stratisd/runs/2058419611?check_suite_focus=true#step:9:375).

2021-03-08 19:28 UTC, mulkieran requested changes
Just one change...then this should be ready to go.

2021-03-08 21:33 UTC, jbaublitz commented on src/engine/strat_engine/tests/util.rs
> +                    let dm_name = match DmName::new(&name) {
Resolved.

2021-03-09 00:10 UTC, mulkieran requested changes
Looks good! Please close and open a final PR.

2021-03-09 13:12 UTC, closed without merging