Fix for hanging in D-Bus code
stratis-storage/stratisd pull request #2585
Opened 2021-05-11 02:44 UTC by jbaublitz

2021-05-11 02:52 UTC, jbaublitz commented
@mulkieran This is not quite ready for review yet but I wanted to put up what I have so far. There's an ugly panic message that happens when `ctrl-C` is issued. I think I can resolve this by changing the `Arc<AtomicBool>` to a `tokio::sync::watch::channel`-based notification when `ctrl-C` is received. My understanding is that the panic message is due to the timeout future trying to start on a Runtime that's already shutting down. The channel-based approach should allow us to block without a timeout and select whichever future returns first. I'll give that a shot tomorrow.

2021-05-12 01:52 UTC, mulkieran requested changes
Looks good so far. Two minor comments. Will need one more pass.

2021-05-12 13:28 UTC, jbaublitz commented on src/stratis/run.rs
> +async fn signal_thread(trigger: Sender<bool>) {
Ah yes! Will do.

2021-05-12 13:30 UTC, jbaublitz commented on src/stratis/run.rs
> +        let (trigger, should_exit) = channel(2);
We only have two instances of the sender side of things and each one can only ever send exactly one message. I've verified that we will never send more than two for that reason. We can increase it, but it doesn't add anything from my point of view.

2021-05-12 17:43 UTC, jbaublitz commented on src/stratis/run.rs
> +async fn signal_thread(trigger: Sender<bool>) {
Resolved.

2021-05-12 17:50 UTC, jbaublitz commented on src/stratis/run.rs
> +        let (trigger, should_exit) = channel(2);
I actually think I missed adding in the second `send` invocation after the `select` macro in `run.rs`. I'll add that. Thanks for catching that!

2021-05-12 19:52 UTC, mulkieran requested changes
This looks ready to go! Please close and open a final PR.

2021-05-12 21:12 UTC, mulkieran requested changes
I ran into an odd problem; please see https://github.com/stratis-storage/stratisd/pull/2590 for a suggestion that might make sense.

The problem was an occasional ERROR log entry 

```[2021-05-12T20:01:39Z ERROR libstratis::stratis::ipc_support::dbus_support] The tree handling thread exited...```

on shutting down stratisd. The change I've put up seems to make that intermittent error disappear.

2021-05-13 01:58 UTC, mulkieran commented
@jbaublitz Other than commit https://github.com/stratis-storage/stratisd/pull/2590/commits/6acc957a359fbb176fb37452298bf15b806365bc suggestion, this looks ready to go. Feel free to drop the ```debug!``` line, I don't think it's really all that useful.

2021-05-13 12:16 UTC, jbaublitz commented
@mulkieran I changed the commit slightly because the thread exit logging has always been a little strange. I'll wait till you take a look at the most recent commit to put up a final PR.

2021-05-13 13:30 UTC, mulkieran requested changes
Looks good! Please close and open final PR.

2021-05-13 13:31 UTC, closed without merging