Add ability to rebind to keyring passphrases and Clevis
stratis-storage/stratisd pull request #2633
Opened 2021-06-02 15:37 UTC by jbaublitz

Closes #2358 
Supersedes #2604

2021-06-18 17:03 UTC, mulkieran commented
@jbaublitz Please rebase here when convenient.

2021-06-18 17:18 UTC, jbaublitz commented
@mulkieran Rebased.

2021-06-22 17:52 UTC, mulkieran commented
@jbaublitz Could you rebase again. The rebase must have occurred just when GitHub Actions started to have trouble.

2021-06-23 13:20 UTC, jbaublitz commented
@mulkieran I've rebased and I'll put it back in review once tests have passed.

2021-06-23 15:21 UTC, jbaublitz commented
@mulkieran Back in review.

2021-06-29 00:30 UTC, mulkieran commented
@jbaublitz Please rebase when you get the chance.

2021-06-29 01:23 UTC, mulkieran requested changes
Code looks great...I have two requests for additional comments and one request for comment.

In the stratis-cli PR https://github.com/stratis-storage/stratis-cli/pull/800 I assume that the user will only want to rebind w/ tang and the man page reflects this. But in this PR, the rebinding occurs with whatever Clevis configuration is present. Should we decide to:
1. Make the CLI less specific?
2. Return an error if the configuration is not for tang?

We allow any sort of configuration to be passed when binding via the API. So it seems like the API should be equally general when rebinding. However, I can not persuade myself that rebinding with tpm2 makes any sense, so that the call to "clevis luks regen" should always return an error in that case. If it does return an error then stratisd will return an error on the D-Bus and that will be, up to a point (module the ugliness of clevis error strings), the right behavior.

Anyhow, I've asked for your review on https://github.com/stratis-storage/stratis-cli/pull/800 in case you think the CLI side should be less specific.

But I'm not sure that what we have here isn't the best choice available; the cleanest and most consistent solution.

2021-06-29 17:07 UTC, mulkieran requested changes
Additional changes look great!

Could you grab the commit from here: https://github.com/stratis-storage/stratisd/pull/2682/commits/ef7ca83e6a3454a8fb0954dd88016c6df732289e.

Also, could you confirm that you would expect the thumbprint displayed by the stratisd report method to be the same before and after a rebind using tang? The theory is that the thumbprint is associated with the identification of the tang server, not with the particular keys that the tang server is publishing and so should be expected to remain constant while the tang server itself remains constant.

2021-06-29 18:11 UTC, jbaublitz commented on src/engine/strat_engine/backstore/crypt/shared.rs
> +            // The above cast is a work around for bug in libcryptsetup-rs
Resolved.

2021-06-29 18:11 UTC, jbaublitz commented on src/engine/strat_engine/backstore/blockdevmgr.rs
> +    /// reverts all of the devices if there is a failure.
Resolved.

2021-06-29 19:48 UTC, jbaublitz commented
> Additional changes look great!
> 
> Could you grab the commit from here: [ef7ca83](https://github.com/stratis-storage/stratisd/commit/ef7ca83e6a3454a8fb0954dd88016c6df732289e).
> 
> Also, could you confirm that you would expect the thumbprint displayed by the stratisd report method to be the same before and after a rebind using tang? The theory is that the thumbprint is associated with the identification of the tang server, not with the particular keys that the tang server is publishing and so should be expected to remain constant while the tang server itself remains constant.

This is now resolved. I didn't properly update the cached data structure after performing the action!

2021-06-29 20:54 UTC, mulkieran reviewed
Ok! This looks ready for testing again!

2021-07-01 12:27 UTC, jbaublitz commented
@drckeefe @mulkieran I've confirmed again that removing the old Tang key after calling `RebindClevis` and then issuing `stratis pool unlock clevis` successfully unlocks the device. The issue did appear to be with the custom build of Clevis in my `PATH`.

2021-07-02 19:47 UTC, jbaublitz commented
@drckeefe Rollback bug is fixed.

2021-07-02 20:11 UTC, drckeefe approved these changes

2021-07-07 15:05 UTC, mulkieran requested changes
This is ready to go. Please close and open a new PR for final review.

2021-07-07 15:44 UTC, closed without merging