Migrate FetchProperties values to standard D-Bus properties
stratis-storage/stratisd pull request #2817
Opened 2021-10-20 21:34 UTC by jbaublitz

Closes #2816

2021-11-01 15:05 UTC, jbaublitz commented
@mulkieran All tests passed other than the expected failure. This is ready for review.

2021-11-02 09:46 UTC, mvollmer commented
Thanks, I got this to work quite nicely with Cockpit here: https://github.com/cockpit-project/cockpit/pull/16532

The "key description" now seems to be doubly optional.  It has a signature of  "(b(bs))" as a pool property, and is encoded like this in the LockedPools property:

```
{ "t": "(bv)", "v": [true, {"t": "(bs)", "v": [true,"pool0"]}]}
```

Can you explain what this means?  What is the difference between `[ false, [ false, "" ]` and `[ true, [ false, "" ]`?

2021-11-02 14:22 UTC, jbaublitz commented
> Thanks, I got this to work quite nicely with Cockpit here: [cockpit-project/cockpit#16532](https://github.com/cockpit-project/cockpit/pull/16532)
> 
> The "key description" now seems to be doubly optional. It has a signature of "(b(bs))" as a pool property, and is encoded like this in the LockedPools property:
> 
> ```
> { "t": "(bv)", "v": [true, {"t": "(bs)", "v": [true,"pool0"]}]}
> ```
> 
> Can you explain what this means? What is the difference between `[ false, [ false, "" ]` and `[ true, [ false, "" ]`?

Hi @mvollmer! So the basic idea here is that `StratisResult<Option<KeyDescription>>` is the type internally. If we were to do just a single boolean, it would be unclear whether the key description was set or whether there was an error. We discussed potentially making that a `(bv)` type so that we could make it `(false, [error string])` or `(true, (bool, string))`, but this didn't work very well for two reasons. One is that the formatting that we have in our CLI just doesn't have room for a long error message displaying what went wrong and the other is that Rust still has some error even in the standard library that make cloning/passing around errors impossible. Our wrapper error type inherited this problem as a result. If we were to try to work around this, we would bump into a requirement of stringifying all errors that we're handling in code that needs to report changes to the D-Bus and this gets to be a problem because of the work we've done on establishing an error chain to allow stratisd to react internally to certain errors and drop to a degraded state. Stringifying errors would render this useless. I've done my best to provide this information through other means like our report interface and more robust logging. Just a note that I've already put up a PR for the D-Bus documentation in preparation for 3.0 and I will update it with this information, in particular which booleans mean errors and which mean optional types.

2021-11-02 14:57 UTC, mvollmer commented
> If we were to do just a single boolean, it would be unclear whether the key description was set or whether there was an error.

Ah, I see, thanks!

2021-11-03 10:13 UTC, mvollmer commented
@jbaublitz, I have tested this now a bit more formally, see https://github.com/cockpit-project/cockpit/pull/16532#issuecomment-958774557. As green as it can be!

2021-11-04 17:34 UTC, mulkieran requested changes
Looks great! Two comment requests and one note.

2021-11-04 17:39 UTC, jbaublitz commented on src/dbus_api/api/manager_3_0/api.rs
> +        .on_get(get_version::<E>)
When I added that, it was necessary. I can remove it if it's no longer necessary.

2021-11-04 17:47 UTC, jbaublitz commented
@mulkieran Okay, this should be ready for review!

2021-11-04 18:25 UTC, mulkieran approved these changes

2021-11-04 18:37 UTC, jbaublitz commented
@mulkieran Squashed!

2021-11-04 19:27 UTC, merged