Optimized lock for per-pool locking
stratis-storage/stratisd pull request #2853
Opened 2021-11-24 18:15 UTC by jbaublitz

Follow up to #2788 
Closes #2724

2021-12-10 18:02 UTC, mulkieran requested changes
Also, please grab two additional commits from https://github.com/stratis-storage/stratisd/pull/2873. That's it!

2021-12-10 19:43 UTC, mulkieran requested changes

2021-12-10 19:43 UTC, mulkieran commented on src/engine/structures/lock.rs
> +        trace!("Dropping shared lock {}", type_name::<G>());
Plz insert "on" into for greater consistency with other similar messages, as "Dropping shared lock on {}".

2021-12-10 19:43 UTC, mulkieran commented on src/engine/structures/lock.rs
> +        trace!("Dropping exclusive lock {}", type_name::<G>());
Also "on" here.

2021-12-10 19:43 UTC, mulkieran commented on src/engine/structures/lock.rs
> +pub struct Waiter<U> {
Drop "pub" modifier

2021-12-10 19:43 UTC, mulkieran commented on src/engine/structures/lock.rs
> +pub enum WaitType<U> {
Drop "pub" modifier.

2021-12-13 22:15 UTC, mulkieran approved these changes

2021-12-16 15:26 UTC, jbaublitz commented
Ready for merge.

2021-12-16 16:06 UTC, merged