Fix missing signal for allocated size changes
stratis-storage/stratisd pull request #2865
Opened 2021-12-06 18:47 UTC by jbaublitz

Closes #2863 

Hi @tasleson feel free to verify this one as well! I've tested on my end.

2021-12-06 22:23 UTC, tasleson commented
> Closes #2863
> 
> Hi @tasleson feel free to verify this one as well! I've tested on my end.

I believe this is corrected.  However, I may be doing something wrong as the `TotalPhysicalUsed` is now incorrect again during my testing, but I had to resolve a conflict to apply this fix.  Would it be possible for you to create a branch that has all three fixes applied for me to test to rule out me doing something incorrect?

Thanks

2021-12-07 00:54 UTC, mulkieran requested changes
One request, otherwise, looks good to me.

2021-12-07 00:54 UTC, mulkieran commented on src/dbus_api/pool/shared.rs
> +            handle_action!(pool
I think you need to stick with the ```handle_action!``` variant that takes 3 args.

2021-12-07 14:30 UTC, jbaublitz commented
> > Closes #2863
> > Hi @tasleson feel free to verify this one as well! I've tested on my end.
> 
> I believe this is corrected. However, I may be doing something wrong as the `TotalPhysicalUsed` is now incorrect again during my testing, but I had to resolve a conflict to apply this fix. Would it be possible for you to create a branch that has all three fixes applied for me to test to rule out me doing something incorrect?
> 
> Thanks

I am about to rebase this one and the other fix is merged so this branch should resolve those issues. I am still unsure of what the best fix is for #2864 in terms of the MDV, but I am considering putting up a PR that resolves #2824 and the MDV issue. I think it would make sense to resolve a lot of the retry errors all at once. I can rebase one of the branches onto the other so you can test it.

2021-12-07 18:25 UTC, mulkieran approved these changes

2021-12-07 18:26 UTC, tasleson commented
@jbaublitz With these two commits cherry-picked on master I'm getting a failure with `TotalPhysicalUsed`, but the `AllocatedSize` is correct.

This is the utility output below (I added dumping object state on object add signal), starting from blank state and issuing

```bash
./stratis pool create the_pool /dev/sdb /dev/sdc
# ~92.5 second delay
./stratis pool add-data the_pool /dev/sdd

```

```
# ./oversight.py org.storage.stratis3 /org/storage/stratis3
[1638900828.220198][17.526301]: Object add: /org/storage/stratis3/0
[1638900828.220356][0.000157]:  
[1638900828.220394][0.000038]: object /org/storage/stratis3/0
[1638900828.220439][0.000046]: Interface org.storage.stratis3.pool.r0
[1638900828.220494][0.000055]: 	AllocatedSize: 2147483648
[1638900828.220526][0.000031]: 	AvailableActions: fully_operational
[1638900828.220601][0.000076]: 	ClevisInfo: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.Struct((dbus.String(''), dbus.String('')), signature=None)), signature=None)), signature=None, variant_level=1)
[1638900828.220641][0.000040]: 	Encrypted: 0
[1638900828.220669][0.000028]: 	HasCache: 0
[1638900828.220715][0.000046]: 	KeyDescription: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None)), signature=None, variant_level=1)
[1638900828.220782][0.000067]: 	Name: the_pool
[1638900828.220810][0.000029]: 	TotalPhysicalSize: 2147483648
[1638900828.220925][0.000115]: 	TotalPhysicalUsed: dbus.Struct((dbus.Boolean(True), dbus.String('43655168')), signature=None, variant_level=1)
[1638900828.220963][0.000037]: 	Uuid: 7441c6dbe7c9406dba1a703061251a13
[1638900828.221305][0.000342]: Object add: /org/storage/stratis3/1
[1638900828.221348][0.000043]:  
[1638900828.221378][0.000030]: object /org/storage/stratis3/1
[1638900828.221420][0.000042]: Interface org.storage.stratis3.blockdev.r0
[1638900828.221472][0.000053]: 	Devnode: /dev/sdb
[1638900828.221523][0.000051]: 	HardwareInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900828.221558][0.000035]: 	InitializationTime: 1638900828
[1638900828.221589][0.000031]: 	PhysicalPath: /dev/sdb
[1638900828.221618][0.000029]: 	Pool: /org/storage/stratis3/0
[1638900828.221649][0.000031]: 	Tier: 0
[1638900828.221679][0.000030]: 	TotalPhysicalSize: 1073741824
[1638900828.221813][0.000134]: 	UserInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900828.221856][0.000043]: 	Uuid: 2290c6ace5534d8fb1c8fb03bacf9600
[1638900828.222599][0.000742]: Object add: /org/storage/stratis3/2
[1638900828.222707][0.000108]:  
[1638900828.222775][0.000067]: object /org/storage/stratis3/2
[1638900828.222819][0.000045]: Interface org.storage.stratis3.blockdev.r0
[1638900828.222874][0.000055]: 	Devnode: /dev/sdc
[1638900828.223006][0.000131]: 	HardwareInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900828.223045][0.000040]: 	InitializationTime: 1638900828
[1638900828.223452][0.000407]: 	PhysicalPath: /dev/sdc
[1638900828.223507][0.000055]: 	Pool: /org/storage/stratis3/0
[1638900828.223540][0.000033]: 	Tier: 0
[1638900828.223569][0.000029]: 	TotalPhysicalSize: 1073741824
[1638900828.224033][0.000464]: 	UserInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900828.224401][0.000368]: 	Uuid: a2b9093e461a41ef8452927267f4879d
[1638900831.223982][2.999581]: Validating objects entry
[1638900831.331595][0.107613]: Validating objects exit 0.107606
[1638900923.911175][92.579581]: /org/storage/stratis3/0[org.storage.stratis3.pool.r0][TotalPhysicalSize] = 2201169690624
[1638900923.911308][0.000132]: /org/storage/stratis3/0[org.storage.stratis3.pool.r0][AllocatedSize] = 2201169690624
[1638900923.911431][0.000123]: Object add: /org/storage/stratis3/3
[1638900923.911488][0.000057]:  
[1638900923.911512][0.000024]: object /org/storage/stratis3/3
[1638900923.911531][0.000020]: Interface org.storage.stratis3.blockdev.r0
[1638900923.911552][0.000020]: 	Devnode: /dev/sdd
[1638900923.911572][0.000021]: 	HardwareInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900923.911589][0.000017]: 	InitializationTime: 1638900923
[1638900923.911596][0.000007]: 	PhysicalPath: /dev/sdd
[1638900923.911620][0.000024]: 	Pool: /org/storage/stratis3/0
[1638900923.911637][0.000017]: 	Tier: 0
[1638900923.911693][0.000056]: 	TotalPhysicalSize: 2199022206976
[1638900923.911716][0.000023]: 	UserInfo: dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None, variant_level=1)
[1638900923.911787][0.000071]: 	Uuid: e40136a5a5504bca8f339397eba0b352
[1638900927.349978][3.438191]: Validating objects entry
[1638900927.456043][0.106064]: Property (TotalPhysicalUsed) mismatch objectmgr dbus.Struct((dbus.Boolean(True), dbus.String('2244644864')), signature=None, variant_level=1) !=  signal value: dbus.Struct((dbus.Boolean(True), dbus.String('43655168')), signature=None) object: /org/storage/stratis3/0
[1638900927.456151][0.000108]: Signal db
[1638900927.456178][0.000027]:  
[1638900927.456198][0.000020]: object /org/storage/stratis3/0
[1638900927.456228][0.000030]: Interface org.storage.stratis3.pool.r0
[1638900927.456264][0.000035]: 	AllocatedSize: 2201169690624
[1638900927.456283][0.000019]: 	AvailableActions: fully_operational
[1638900927.456388][0.000105]: 	ClevisInfo: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.Struct((dbus.String(''), dbus.String('')), signature=None)), signature=None)), signature=None, variant_level=1)
[1638900927.456453][0.000065]: 	Encrypted: 0
[1638900927.456504][0.000051]: 	HasCache: 0
[1638900927.456567][0.000063]: 	KeyDescription: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None)), signature=None, variant_level=1)
[1638900927.456656][0.000089]: 	Name: the_pool
[1638900927.456713][0.000056]: 	TotalPhysicalSize: 2201169690624
[1638900927.456774][0.000061]: 	TotalPhysicalUsed: dbus.Struct((dbus.Boolean(True), dbus.String('43655168')), signature=None, variant_level=1)
[1638900927.456995][0.000221]: 	Uuid: 7441c6dbe7c9406dba1a703061251a13
[1638900927.457089][0.000094]: GetManagedObjects
[1638900927.457157][0.000069]:  
[1638900927.457206][0.000049]: object /org/storage/stratis3/0
[1638900927.457253][0.000047]: Interface org.storage.stratis3.pool.r0
[1638900927.457307][0.000054]: 	AllocatedSize: 2201169690624
[1638900927.457360][0.000053]: 	AvailableActions: fully_operational
[1638900927.457435][0.000076]: 	ClevisInfo: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.Struct((dbus.String(''), dbus.String('')), signature=None)), signature=None)), signature=None, variant_level=1)
[1638900927.457515][0.000080]: 	Encrypted: 0
[1638900927.457694][0.000180]: 	HasCache: 0
[1638900927.457987][0.000293]: 	KeyDescription: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.String('')), signature=None)), signature=None, variant_level=1)
[1638900927.458059][0.000072]: 	Name: the_pool
[1638900927.458111][0.000053]: 	TotalPhysicalSize: 2201169690624
[1638900927.458210][0.000098]: 	TotalPhysicalUsed: dbus.Struct((dbus.Boolean(True), dbus.String('2244644864')), signature=None, variant_level=1)
[1638900927.458347][0.000137]: 	Uuid: 7441c6dbe7c9406dba1a703061251a13
[1638900927.458573][0.000226]: Validating objects exiting ON ERROR! duration = 0.108590
[1638900927.995612][0.537039]: **** Dumping signal db
[1638900927.995671][0.000058]:  
[1638900927.995685][0.000014]: object /org/storage/stratis3/0
[1638900927.995703][0.000018]: Interface org.storage.stratis3.pool.r0
[1638900927.995725][0.000022]: 	AllocatedSize: 2201169690624
[1638900927.995736][0.000010]: 	AvailableActions: fully_operational
[1638900927.995864][0.000128]: 	ClevisInfo: dbus.Struct((dbus.Boolean(True), dbus.Struct((dbus.Boolean(False), dbus.Struct((dbus.String(''), dbus.String('')), signature=None)), signatu [...]

2021-12-13 18:48 UTC, jbaublitz commented
@tasleson @mulkieran I'm going to rebase and resolve conflicts but I've verified that this PR resolves the problem.

2021-12-20 18:34 UTC, mulkieran commented
Thanks, it is in.

2022-01-04 15:27 UTC, jbaublitz commented
@tasleson @mulkieran Can I get one last review on this now that the conflicts are resolved?

2022-01-04 18:59 UTC, mulkieran approved these changes

2022-01-05 00:28 UTC, mulkieran commented
@jbaublitz Plz rebase, thx.

2022-01-05 17:25 UTC, jbaublitz commented
@mulkieran Rebased!

2022-01-05 19:48 UTC, mulkieran commented
@jbaublitz I'm feeling concerned that both the ```checks_with_udev``` tests seem to have been stalled on ```test engine::strat_engine::pool::tests::loop_test_add_datadevs```. What do you think?

2022-01-05 20:16 UTC, jbaublitz commented
@mulkieran The thin pool rework PR tests stalled at a different point. I'm wondering if there's some infrastructure issues with Github Actions right now.

2022-01-06 19:20 UTC, mulkieran approved these changes

2022-01-06 20:31 UTC, merged