libcryptsetup 0.6.0 changes
stratis-storage/stratisd pull request #3075
Opened 2022-08-09 18:50 UTC by jbaublitz

Related to stratis-storage/libcryptsetup-rs#228

2022-08-10 14:01 UTC, mulkieran commented
Changes all look good.

2022-08-11 15:36 UTC, bmr-cymru approved these changes

2022-08-25 21:47 UTC, mulkieran requested changes
@jbaublitz Plz rebase and make the requested edits, and I'll merge this.

2022-08-25 21:47 UTC, mulkieran commented on .github/workflows/cargo.yml
> +              COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../stratisd_proc_macros/Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-category low --ignore-high libcryptset
Drop the top two edits, these check stratisd_proc_macros.

2022-08-25 21:47 UTC, mulkieran commented on Cargo.toml
> +git = "https://github.com/jbaublitz/libcryptsetup-rs"
And drop these, of course.

2022-08-25 23:15 UTC, mulkieran commented
https://www.githubstatus.com/...

2022-08-26 14:12 UTC, merged