Replace SetUserInfo with settable property
stratis-storage/stratisd pull request #3131
Opened 2022-10-10 19:49 UTC by jbaublitz

Closes #3126

2022-10-11 17:58 UTC, mulkieran requested changes
Two questions, otherwise review complete.

2022-10-12 12:36 UTC, jbaublitz commented on src/dbus_api/blockdev/blockdev_3_3/api.rs
> +        .emits_changed(EmitsChangedSignal::False)
Ah yes, you're right. Thanks!

2022-10-12 21:16 UTC, jbaublitz commented on src/engine/types/actions.rs
> +impl<T> Debug for PropChangeAction<T>
I've addressed the concern you brought up in our meeting. Let me know if you have an issue with the design.

2022-10-13 02:26 UTC, mulkieran requested changes

2022-10-13 02:26 UTC, mulkieran commented on src/dbus_api/blockdev/shared.rs
> +        .map_err(|ref e| MethodErr::failed(e));
I understand how this works but it seems to exploit the coincidence that the blockdev property that needs a pool lock to set is also an Option type and therefore has a ToDisplay implementation.

What about having the EngineAction trait require a to_display() method and define the default implementation as the identity? Then all EngineAction types have the to_display() method and the handle_action macro can make the to_display() call, something like:

```
log::info("{}", a.to_display())
```

The ToDisplay trait can be dropped, in this approach.

This seems tidier and more maintainable to me.

2022-10-13 13:45 UTC, jbaublitz commented on src/dbus_api/blockdev/shared.rs
> +        .map_err(|ref e| MethodErr::failed(e));
It's not really exploiting a coincidence. Originally I left the equivalent to `set_pool_level_blockdev_property_to_display` that requires the `Display` trait instead of the `ToDisplay` trait but it was unused. We can always add it back in in addition to the existing method if we eventually need `Display` types as well. That other method can then be used at the top level of the property set definition just like it is for `UserInfo`. I'm not entirely convinced that it's any more tidy to require all of that boilerplate code for types that don't really need the definition when it's just the identity function. Another consideration just to keep in mind is that if we define `.to_display()` for all types, we're going to introduce unnecessary clones (allocations) for any data type that doesn't implement `Copy`. If we can simply dispatch to different handlers for `Display` and `ToDisplay`, we avoid this.

2022-10-13 17:35 UTC, jbaublitz commented
Yep, already working on it. I bumped into a weird situation where `prop_conv` disappeared in the rebase so I've had to start over. I also think I need to move some code to `prop_conv` in this PR.

2022-10-17 01:31 UTC, mulkieran approved these changes

2022-10-17 18:53 UTC, bmr-cymru approved these changes

2022-10-17 21:04 UTC, merged