Add encrypted cache support
stratis-storage/stratisd pull request #3137
Opened 2022-10-14 18:28 UTC by jbaublitz

Closes #3136

2022-11-23 18:24 UTC, mulkieran commented
@jbaublitz Plz rebase when you get the chance, thx.

2022-12-01 22:59 UTC, mulkieran commented
For initializing cache after pool has created we decided that it would count as a bug if a client using D-Bus revision 4 or below found that they could create a cache even if the pool was encrypted. We'll have the D-Bus layer pass a boolean to the engine, to indicate which decision it should make.

2022-12-08 17:26 UTC, mulkieran requested changes
Also one minor comment about tests...

2022-12-08 18:29 UTC, jbaublitz commented on src/engine/strat_engine/pool.rs
> +        pool.init_cache(uuid, name, paths1, false).unwrap();
If we want to keep it unchanged, that should be `false`. My goal was to not change the tests at all.

2022-12-13 14:34 UTC, mulkieran commented on src/engine/strat_engine/pool.rs
> +        pool.init_cache(uuid, name, paths1, false).unwrap();
I think it is better to change to what stratisd will be doing from now through the foreseeable future, which is always supporting an encrypted cache. In the case where more ```init_cache``` invocations are put in our tests, ```true``` will always be the correct argument (unless we're doing some backwards compatibility testing in the unit tests, which is highly unlikely).

2022-12-13 14:40 UTC, jbaublitz commented on src/engine/strat_engine/pool.rs
> +        pool.init_cache(uuid, name, paths1, false).unwrap();
Okay that sounds good!

2022-12-13 18:45 UTC, jbaublitz commented on src/engine/strat_engine/pool.rs
> +        pool.init_cache(uuid, name, paths1, false).unwrap();
Resolved.

2022-12-15 15:37 UTC, mulkieran approved these changes

2022-12-15 17:33 UTC, merged