Clean up for AllOrSomeLock
stratis-storage/stratisd pull request #3166
Opened 2022-11-10 19:08 UTC by jbaublitz

2022-11-11 02:53 UTC, mulkieran requested changes
I think it might be useful to add a comment explaining why the UnsafeCell is necessary. Also, please see the one review comment.

2022-11-11 02:53 UTC, mulkieran commented on src/engine/structures/lock.rs
> +impl<U, T> Unpin for AllRead<U, T>
I _think_ this might be unnecessary.

2022-11-11 15:22 UTC, jbaublitz commented on src/engine/structures/lock.rs
> +impl<U, T> Unpin for AllRead<U, T>
It is! Thanks for catching that!

2022-11-14 01:36 UTC, mulkieran approved these changes

2022-11-14 01:50 UTC, merged