remove dependency on udevadm
stratis-storage/stratisd pull request #3173
Opened 2022-11-18 14:36 UTC by leseb

Currently stratisd needs udevadm to run correctly, see:

```
[2022-11-17T13:06:49Z ERROR stratisd::stratis::run] Failed to start up
stratisd engine: Unable to find executable "udevadm" in any of
"/usr/sbin", "/sbin", "/usr/bin", "/bin"; exiting
```

However, this binary is never used while stratisd operates. It looks like this is only used for the test framework and nothing else. So we remove this dependency as well as removing the need for the binary itself in the tests.

Disclaimer: I'm very new with both Stratis and Rust so please bear with me.

Signed-off-by: Sébastien Han <seb@redhat.com>

2022-11-18 14:54 UTC, mulkieran commented
@leseb Thanks for the PR! We have two targets in our Makefile, "fmt" and "clippy" and we enforce their rules in our CI. Running those in your development environment will save you the trouble of unnecessary round trips w/ our CI.

2022-11-22 16:42 UTC, jbaublitz reviewed
I'm unsure whether this conflicts with the udev sync work, but if that PR is still using udevadm and CI doesn't fail for this PR, this may be okay to merge prior to that.

2022-11-22 16:42 UTC, jbaublitz commented on src/engine/strat_engine/udev.rs
> +    }
Mainly stylistic, but I'd think this return type should either be `StratisResult<()>` or `bool`. I don't see any case where `Ok(false)` is returned.

2022-12-02 15:31 UTC, jbaublitz requested changes
After these are handled, I think we can accept this PR.

2022-12-02 15:31 UTC, jbaublitz commented on src/engine/strat_engine/cmd.rs
> +use serde_json::Value;
We generally want the imports to be separated into the following categories:

`std`

external crates (like libc, serde_json)

crates that are external that we develop (like devicemapper)

`crate`

all separated by a newline so they're ordered appropriately within those categories.

2022-12-02 15:31 UTC, jbaublitz commented on src/engine/strat_engine/udev.rs
> +    // Path of udev queue's file, typically this file is empty, it just asses that udev events are still
This should be "it just assesses"

2022-12-02 15:33 UTC, jbaublitz commented
Oops, missed that CI is failing. We'll have to investigate that first too @leseb.

2022-12-08 14:39 UTC, jbaublitz commented
@leseb Looks like we've fixed all of the failures by doing that except for `check_with_tang` which appears to not have been modified. If you apply the same changes there, I have a feeling that we should be good to go with CI.

2023-01-03 00:48 UTC, mulkieran commented
I think we're trying to fix up some CI problems, see #3211

2023-01-03 23:25 UTC, mulkieran commented
The CI problems seem to be caused by the non-cli implementation of settle starting and finishing too fast. We aren't sure, but it might be that the udev synchronization work would resolve this problem.

2023-01-05 08:40 UTC, leseb commented
> The CI problems seem to be caused by the non-cli implementation of settle starting and finishing too fast. We aren't sure, but it might be that the udev synchronization work would resolve this problem.

Agreed, hence the retry in this PR. This might be environment specific since the runners are small VMs, something we might not encounter on larger machines. Also, AFAIC this is only executed during the unit tests so retry is not uncommon in CI :).

2023-01-05 14:49 UTC, leseb commented
Closing this PR since it will soon be superseded by another implementation (udev synchronization improvements). We may re-open in the future if necessary. Thanks @mulkieran @jbaublitz for your support on this.

2023-01-05 14:49 UTC, closed without merging