Update lowest supported Rust to 1.66.1
stratis-storage/stratisd pull request #3234
Opened 2023-01-19 19:15 UTC by bgurney-rh

Related: stratis-storage/project#489

2023-01-20 00:40 UTC, mulkieran requested changes
Better add rust-version to ``` stratisd_proc_macros``` Cargo.toml also.

2023-01-20 22:25 UTC, mulkieran approved these changes

2023-01-26 19:54 UTC, bgurney-rh commented
Rebased.

2023-01-26 20:01 UTC, mulkieran approved these changes

2023-01-26 21:59 UTC, merged