Revert allocation transaction committed
stratis-storage/stratisd pull request #3491
Opened 2023-11-01 20:27 UTC by jbaublitz

Related to #3274

2023-11-02 01:54 UTC, jbaublitz commented
/packit test

2023-11-02 13:58 UTC, jbaublitz commented
/packit test

2023-11-02 14:31 UTC, jbaublitz commented
/packit test

2023-11-06 18:02 UTC, mulkieran requested changes
This all looks good. One minor docs request.

2023-11-08 15:02 UTC, jbaublitz commented on src/engine/strat_engine/backstore/data_tier.rs
>      /// block devices belonging to the data tier. Return Some(_) if requested
Resolved.

2023-11-08 15:04 UTC, jbaublitz commented
I also made one PR revision that appeared to be required to avoid a panic in cases where we incorrectly calculate the amount of space to allocate from the backstore to the thinpool. I bumped into this due to a bug in #3274 that I intend to fix but it seems better to handle that case with an error in case we introduce another bug like that in the future.

2023-11-08 15:19 UTC, jbaublitz commented
Putting back in progress to look into one additional piece brought up by #3274.

2023-11-08 23:39 UTC, jbaublitz commented
/packit test

2023-11-09 14:47 UTC, jbaublitz commented
I think this is ready for final review.

2023-11-13 16:22 UTC, jbaublitz commented
/packit test

2023-11-15 00:38 UTC, mulkieran commented
@jbaublitz Plz rebase when you get the chance.

2023-11-15 14:32 UTC, jbaublitz commented
/packit test

2023-11-16 01:11 UTC, mulkieran approved these changes

2023-11-16 01:12 UTC, mulkieran commented
@jbaublitz Plz rebase when you get the chance and we can merge this.

2023-11-16 15:36 UTC, merged