Add D-Bus method to return Stratis pool-level metadata
stratis-storage/stratisd pull request #3599
Opened 2024-04-25 20:04 UTC by mulkieran

2024-04-25 20:19 UTC, mulkieran commented
I'm not convinced that it would be wrong to have a parameter to modify what the method returns. For example, what if in future we do want to get what the metadata on the devices is and compare it with the metadata to write. We do not need to implement this right now, but we might want the flexibility to add it without adding another method.

2024-05-02 13:35 UTC, jbaublitz requested changes
I had a mix of requests and discussion points, but other than that this looks reasonable to me.

2024-05-02 13:44 UTC, mulkieran commented on src/engine/strat_engine/backstore/blockdev.rs
> +        self.bda = bda;
This is a really important point. The last update time for the pool-level metadata for a particular device can not be determined unless you re-read the BDA. And if you re-read the BDA, then it seems like you ought to cache it. Another, probably better solution, is to cache the BDA when the pool-level metadata is written. If that seems like a better solution, I can try that separately. If that were done, then the cached BDA would be able to be used in this PR and the simplifications that you point out would be available.

2024-05-02 14:12 UTC, jbaublitz commented on src/engine/strat_engine/backstore/blockdev.rs
> +        self.bda = bda;
I think I'd prefer refreshing when the pool level metadata is written. I checked our existing usage of the bda, and I don't think we have a bug currently, but I was unaware of this side effect, and I think we're asking for trouble if we don't keep our cached data structures up to date as soon as they're written.

2024-05-03 00:01 UTC, mulkieran commented
@jbaublitz https://github.com/stratis-storage/stratisd/pull/3606 which caches the BDA is up for your review.

2024-05-03 18:25 UTC, mulkieran commented on src/dbus_api/pool/pool_3_7/api.rs
> +        .out_arg(("results", "ay"))
I feel like returning it as String w/out check is actually wrong. So, I'll try returning as String, but error in the unlikely case that it is not valid utf-8.

2024-05-03 20:33 UTC, jbaublitz approved these changes

2024-05-06 00:22 UTC, merged