Do verification on the stratisd side for Clevis configs to avoid hanging
stratis-storage/stratisd pull request #3613
Opened 2024-05-07 15:34 UTC by jbaublitz

Related to latchset/clevis#241

2024-05-08 20:09 UTC, mulkieran requested changes
This all makes sense to me. My only concern is that it might be possible to pass a config that causes a stack overflow during the recursive execution of ```all_tang_configs_have_thp```. I think there should be some way to prevent that from happening.

2024-05-08 20:47 UTC, jbaublitz commented
That is arguably already possible in other parts of the code given that we take a similar recursive approach when parsing Clevis tokens from disk to provide the reconstructed config to the user over the D-Bus. How would you recommend approaching preventing this in both cases? Adding a parameter to limit the number of recursions we can reach?

2024-05-08 21:13 UTC, mulkieran commented
> That is arguably already possible in other parts of the code given that we take a similar recursive approach when parsing Clevis tokens from disk to provide the reconstructed config to the user over the D-Bus. How would you recommend approaching preventing this in both cases? Adding a parameter to limit the number of recursions we can reach?

Until now, we weren't recursively exploring the config, we were essentially passing it directly through to Clevis. But now that we're recursively exploring something that is sent over the D-Bus, I think that the additional caution is warranted. I'm not sure if parsing the Clevis tokens from disk is analogous, but it may well be.

A recursion limit would be fine, I think.

2024-05-14 15:23 UTC, jbaublitz commented
@martinpitt Is this a known issue with cockpit? It seems to be affecting all new PRs with stratisd. @mulkieran believes this is not a problem in our master branch.

2024-05-16 17:47 UTC, merged