Snapshot support
stratis-storage/stratisd pull request #3694
Opened 2024-09-25 21:23 UTC by mulkieran

2024-09-26 01:46 UTC, mulkieran commented
We expect all tests to pass

2024-09-26 02:40 UTC, mulkieran commented
Previous test failure was due to nothing worse than a missing chunk of test...

2024-09-26 17:37 UTC, mulkieran commented
Failing tests were caused by PoolStart call with extra fd in Python test code...

2024-09-27 02:05 UTC, mulkieran commented
Squashed to eliminate some switchbacks

2024-10-01 20:39 UTC, jbaublitz reviewed
I'm still going through the PR but so far just one comment.

2024-10-01 20:39 UTC, jbaublitz commented on src/engine/strat_engine/serde_structs.rs
> +    pub merge: Option<bool>,
As we discussed, I think this could be with something like `#[serde(default)]`

2024-10-02 13:25 UTC, mulkieran commented
@jbaublitz back at you...

2024-10-02 15:36 UTC, jbaublitz requested changes
I think I've finished reviewing this, so after these changes are addressed I'll approve it.

2024-10-02 17:08 UTC, mulkieran commented on src/engine/strat_engine/thinpool/thinpool.rs
> +                            "Failed to delete space allocated for deleted origin filesystem with UUID {:} and thin id {:}: {:?} after revert",
Not all of the values can be inline, because Rust will not evaluate the '.' operator in a format string. I think I should leave this one as is.

2024-10-02 17:28 UTC, jbaublitz commented on src/engine/sim_engine/pool.rs
> +    fn set_fs_merge_scheduled(
Whoops! Missed that part. I was just looking at the mdv piece at the end. Disregard.

2024-10-02 17:29 UTC, jbaublitz commented on src/engine/strat_engine/thinpool/thinpool.rs
> +                            "Failed to delete space allocated for deleted origin filesystem with UUID {:} and thin id {:}: {:?} after revert",
Yes, I was suggesting inline the ones you can. Would you prefer to leave them all out if you leave some of them out?

2024-10-02 17:46 UTC, mulkieran commented on src/engine/strat_engine/thinpool/thinpool.rs
> +                            "Failed to delete space allocated for deleted origin filesystem with UUID {:} and thin id {:}: {:?} after revert",
I've not thought about this before. Let's make a rule and stick to it. If inlining as many as can be inlined is the rule we want, I'm happy to go with that.

2024-10-02 21:24 UTC, mulkieran commented
@jbaublitz I decided to inline all the format strings that I could inline that were introduced by this PR.

2024-10-03 13:32 UTC, mulkieran commented
@jbaublitz Ok. This is ready again.

2024-10-03 14:29 UTC, jbaublitz approved these changes

2024-10-03 14:57 UTC, bmr-cymru approved these changes

2024-10-03 17:10 UTC, mulkieran commented
squashed...

2024-10-03 20:02 UTC, mulkieran commented
Gating tests and stratis-cli tests will fail...

2024-10-04 00:57 UTC, mulkieran commented
Only gating tests fail...

2024-10-04 01:29 UTC, mulkieran commented
Gating tests should no longer fail...

2024-10-04 03:13 UTC, mulkieran commented
TMT is stuck on Cockpit tests, merging...

2024-10-04 03:13 UTC, merged