Accept "adv" key as well as "thp" key
stratis-storage/stratisd pull request #3701
Opened 2024-10-14 19:29 UTC by mulkieran

2024-10-14 21:01 UTC, jbaublitz requested changes

2024-10-15 00:05 UTC, mulkieran commented on src/engine/strat_engine/backstore/backstore.rs
> +                && existing_info.get("url") == parsed_config.get("url")
Yes. I think we should drop that URL check altogether. I updated the code and the commit message.

2024-10-15 03:52 UTC, mulkieran commented
@jbaublitz It's ready for you again. Please note additional source code change: https://github.com/stratis-storage/stratisd/pull/3701/commits/27cbcda5322e81b2a77c9d4a643a64f09dc554e3 .

2024-10-15 03:52 UTC, mulkieran commented
@mvollmer If you would like to test, please let us know, thx.

2024-10-15 07:31 UTC, mvollmer commented
> @mvollmer If you would like to test, please let us know, thx.

Will do! Thanks for the awesome overnight response!

2024-10-15 08:11 UTC, mvollmer commented
> @mvollmer If you would like to test, please let us know, thx.

Results of manual testing, creating a encrypted Stratis pool in Cockpit bound to tang:

 - stratisd 3.6.8 from Fedora 40, works
 - stratisd from master d7e1805, fails as in #3699 
 - stratisd 3.7.1 from this PR 8160433, works

Thanks!

I'll run some of our CI tests as well.

2024-10-15 08:30 UTC, mvollmer approved these changes
All our tests now pass. Thanks!

2024-10-15 13:19 UTC, jbaublitz approved these changes
I agree that it's probably better to be a little looser with idempotence. I feel like being too specific with something as complicated as the Clevis format may lead to problems down the line.

2024-10-15 13:44 UTC, merged